// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://achiobshriimazcddwdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjaGlvYnNocmlpbWF6Y2Rkd2RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyOTY3MTksImV4cCI6MjA2Nzg3MjcxOX0.S7H2OInvqJ2g62F5pEbGuCNDtscmK9b8Cs5E2Rtw6BI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});